version: '3'
services:
  mariadb:
    image: mariadb:latest
    container_name: bookstoreapplication
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: bookstoreFinalDB
      TZ: Europe/Berlin
    ports:
      - "3308:3306"
    volumes:
      - ./data:/var/lib/mysql